services:
  open-webui:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: open-webui
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - GOOGLE_SHEET_CREDENTIALS=${GOOGLE_SHEET_CREDENTIALS}
      - ENABLE_RAG_WEB_SEARCH=${ENABLE_RAG_WEB_SEARCH}
      - RAG_WEB_SEARCH_ENGINE=${RAG_WEB_SEARCH_ENGINE}
      - RAG_WEB_SEARCH_RESULT_COUNT=${RAG_WEB_SEARCH_RESULT_COUNT}
      - RAG_WEB_SEARCH_CONCURRENT_REQUESTS=${RAG_WEB_SEARCH_CONCURRENT_REQUESTS}
      - SEARXNG_QUERY_URL=${SEARXNG_QUERY_URL}
    ports:
      - "3000:8080"
    volumes:
      - open-webui-data:/app/backend/data
    restart: always
    env_file:
      - .env
    depends_on:
      - searxng
    networks:
      - shared-network

  searxng:
    container_name: searxng
    image: searxng/searxng
    ports:
      - "8081:8080"
    volumes:
      - searxng-config:/etc/searxng:rw
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - shared-network

volumes:
  open-webui-data:
  searxng-config:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./searxng

networks:
  shared-network:
    external: true
